---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xjc.
--- DateTime: 2022/11/5 20:09
---

--比较线程标示与锁中的标示是否一致
if(redis.call('get',KEYS[1]) == ARGV[1])then
    return redis.call('del',KEYS[1])
end
return 0